language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  # remember to change this name if you change it elsewhere (e.g. package.json)
  - mongo mongotomeeting --eval
    'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'change it
    elsewhere (e.g. package.json)
script:
  #- npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: mongotomeeting
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: rTLujoIWX+cS3eh+gg52EdCR88R+zcAivDvwvK49+/f012CsEwYRGfHROG4UDEjtpmWjHR22pzJ+WR1Qaar2ExH5me6xlsy1Un115w5FX57ArOanilBlTr+ChUClW9Q8iTelF14zi5xpV7JVsndQSnDNLS9FKqAoTn4eCwRocLVMTeTDc8pQFT7YHyHe+PN6ZAIHGQ9xMhwPJyBMCoQCY/HZAbKiXgb0n3kFIbmSaMvQSmFHwCz36xepuvHMvfgqgXjLIaWGJPlebmg7nrIgA+LibIUUwq45uSnQJviLix3TxRXp5TKKg2CXPxLjJeFRkotzBOkOl9LTJjVc+htG6FXcppMC9PY6h5oMNre0+R0iTuJnLA3cneqEYeH7whRhgIRiLbUrFp3TsuRAink/CiEorVdlP9/weaLkcvvCGMrC7l435graRHMRSL5Uwtd/2826uyCVieWTDirbCvb8ID0Q3VdcRYq6n1jlLwMbuKe2WAHHMvhxXbOkvBqZiaTa1C2Hm1zSF9/AaProwDegY1AH7VGcOcxjDUioUXMtRYk2F/CtnUCbu3722eD3iftKSzKpcq2ea15sYPHrdQpyhJfZ38NR9OjNSCfCsCgmCkGDNGL30HYfTC9tT9OWWgo7eyYiQjGKNW93BtzmKn501f53lH731PZjuN8XntLfzqE=
